Anykernel changes

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -57,11 +57,14 @@ setup_mountpoint() {
 }
 is_mounted() { $bb mount | $bb grep -q " $1 "; }
 umount_all() {
-  ($bb umount /system;
-  $bb umount -l /system;
-  if [ -e /system_root ]; then
-    $bb umount /system_root;
-    $bb umount -l /system_root;
+  (if ! $BOOTMODE; then
+    umount_apex;
+    $bb umount /system;
+    $bb umount -l /system;
+    if [ -e /system_root ]; then
+      $bb umount /system_root;
+      $bb umount -l /system_root;
+    fi;
   fi;
   umount /vendor;
   umount -l /vendor;
@@ -70,11 +73,61 @@ umount_all() {
     $bb umount -l /data;
   fi) 2>/dev/null;
 }
+mount_apex() {
+  test -d /system/apex || return 1;
+  local apex dest loop minorx num;
+  setup_mountpoint /apex;
+  test -e /dev/block/loop1 && minorx=$(ls -l /dev/block/loop1 | $bb awk '{ print $6 }') || minorx=1;
+  num=0;
+  for apex in /system/apex/*; do
+    dest=/apex/$(basename $apex .apex);
+    test "$dest" == /apex/com.android.runtime.release && dest=/apex/com.android.runtime;
+    mkdir -p $dest;
+    case $apex in
+      *.apex)
+        $bb unzip -qo $apex apex_payload.img -d /apex;
+        $bb mv -f /apex/apex_payload.img $dest.img;
+        $bb mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
+        if [ $? != 0 ]; then
+          while [ $num -lt 64 ]; do
+            loop=/dev/block/loop$num;
+            ($bb mknod $loop b 7 $((num * minorx));
+            $bb losetup $loop $dest.img) 2>/dev/null;
+            num=$((num + 1));
+            $bb losetup $loop | $bb grep -q $dest.img && break;
+          done;
+          $bb mount -t ext4 -o ro,loop,noatime $loop $dest;
+          if [ $? != 0 ]; then
+            $bb losetup -d $loop 2>/dev/null;
+          fi;
+        fi;
+      ;;
+      *) $bb mount -o bind $apex $dest;;
+    esac;
+  done;
+  export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime;
+  export ANDROID_TZDATA_ROOT=/apex/com.android.tzdata;
+  export BOOTCLASSPATH=/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar;
+}
+umount_apex() {
+  test -d /apex || return 1;
+  local dest loop;
+  for dest in $($bb find /apex -type d -mindepth 1 -maxdepth 1); do
+    if [ -f $dest.img ]; then
+      loop=$($bb mount | $bb grep $dest | $bb cut -d" " -f1);
+    fi;
+    ($bb umount -l $dest;
+    $bb losetup -d $loop) 2>/dev/null;
+  done;
+  rm -rf /apex;
+  unset ANDROID_RUNTIME_ROOT ANDROID_TZDATA_ROOT BOOTCLASSPATH;
+}
 restore_env() {
   test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
   test "$savedpre" && export LD_PRELOAD="$savedpre";
   umount_all;
-  ($bb mv -f /system_link /system;
+  ($bb mv -f /apex_link /apex;
+  $bb mv -f /system_link /system;
   $bb mv -f /system_root_link /system_root;
   $bb umount -l /dev/random) 2>/dev/null;
 }
@@ -121,12 +174,19 @@ if [ -f banner ]; then
   ui_print " " " ";
 fi;
 
-ui_print "$(file_getprop anykernel.sh kernel.string)";
+ui_print " ";
+ui_print "================================= "; 
+ui_print " ";
+ui_print " - $(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
+ui_print " "; 
+ui_print "================================= ";
+ui_print " ";
 if [ -f version ]; then
   ui_print " ";
   ui_printfile version;
   ui_print " ";
 fi;
+ui_print " - AnyKernel3 by osm0sis ";
 
 $BOOTMODE || $bb mount -o bind /dev/urandom /dev/random;
 umount_all;
@@ -152,6 +212,7 @@ if is_mounted /system_root; then
   $bb mount -o bind /system_root/system /system;
 fi;
 $bb mount -o ro -t auto /vendor 2>/dev/null;
+$BOOTMODE || mount_apex;
 if ! is_mounted /data; then
   $bb mount /data;
   umount_data=1;
@@ -179,7 +240,7 @@ elif [ ! "$(getprop ro.build.type 2>/dev/null)" ]; then
 fi;
 
 if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
+  ui_print " - Checking device...";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
@@ -187,20 +248,20 @@ if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        ui_print " - Device: $testname";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort " - Unsupported device. Aborting...";
   fi;
 fi;
 
 supported_ver=$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]');
 if [ "$supported_ver" ]; then
-  ui_print "Checking Android version...";
+  ui_print " - Checking Android version...";
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
   if echo $supported_ver | $bb grep -q '-'; then
@@ -218,15 +279,15 @@ if [ "$supported_ver" ]; then
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
+    ui_print " - Android Version: $android_ver";
   else
-    abort " " "Unsupported Android version. Aborting...";
+    abort " - Unsupported Android version. Aborting...";
   fi;
 fi;
 
 supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $bb grep -oE '[0-9]{4}-[0-9]{2}|-');
 if [ "$supported_lvl" ]; then
-  ui_print "Checking Android security patch level...";
+  ui_print " - Checking Android security patch level...";
   android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
   parsed_lvl=$(echo $android_lvl | $bb grep -oE '[0-9]{4}-[0-9]{2}');
   if echo $supported_lvl | $bb grep -q '^\-'; then
@@ -242,11 +303,11 @@ if [ "$supported_lvl" ]; then
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $bb sort -g | $bb grep -n "$parsed_lvl" | $bb grep -q '^2:'; then
     ui_print "$android_lvl" " ";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort " - Unsupported Android security patch level. Aborting...";
   fi;
 fi;
 
-ui_print "Installing Kernel...";
+ui_print " - Installing kernel...";
 core=$($bb grep -oE 'ak.*core.sh' anykernel.sh);
 test -f tools/$core || $bb ln -s $home/tools/ak*-core.sh $home/tools/$core;
 PATH="$home/bin:$PATH" home=$home $bb ash anykernel.sh $2;
@@ -255,11 +316,11 @@ if [ $? != 0 ]; then
 fi;
 
 if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
-  ui_print " " "Pushing modules...";
+  ui_print " - Pushing modules...";
   $bb mount -o rw,remount -t auto /system;
   $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
   cd $home/modules;
-  for module in $(find . -name '*.ko'); dohttps://github.com/sohamxda7/Anykernel3
+  for module in $(find . -name '*.ko'); do
     modtarget=$(echo $module | $bb cut -c2-);
     if [ ! -e $modtarget ]; then
       case $module in
@@ -290,7 +351,9 @@ debugging;
 restore_env;
 
 if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
+  ui_print " - Cleaning up...";
   cleanup;
 fi;
 
-ui_print " " " " "====Predator Kernel Beta 5.3====!";
+ui_print " - Done!";
+ui_print " - Predator Kernel 5.3! ";
